- name: "Ensure dataset tank/certs is unlocked"
  truenas_dataset_unlock:
    dataset_id: "tank/certs"
    passphrase: "{{ vault.truenas_certs_volume_passphrase }}"
    api_key: "{{ vault.trunas_certs_deploy_api_key }}"
    host: "truenas.i.krel.ing"
  delegate_to: localhost
